# either set server.port as system property using command line option to jvm -Dserver.port=6583
# java -Dserver.port=6583 -jar target/activity-server-1.0.jar
# java -jar target/activity-server-1.0.jar --server.port=6583
server:
  port: 8081
  servlet:
    contextPath: /rain-server
  error:
    whitelabel:
      enabled: false


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis默认情况下有16个分片，配置具体使用的分片，默认为0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
