# either set server.port as system property using command line option to jvm -Dserver.port=8081
# java -Dserver.port=8081 -jar target/official-website-server-1.0.jar
# java -jar target/official-website-server-1.0.jar --server.port=8081
server:
  port: 8081
  servlet:
    contextPath: /official-website-server
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.88.254.43:3306/mythware_edu?useUnicode=true&&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql